\begin{appendix}
\section{Generation performance}\label{generation-performance}

This appendix provides the raw generation performance for all
experiments in tables A1, A2, and A3.

\begin{table}
\begin{center}
\begin{threeparttable}
\caption{\label{tab:appendix-pdl9-generation}Mean percentage of regular transitions generated in Experiment 1, excluding repetions. Standard deviations are given in parentheses.}
\begin{tabular}{lll}
\toprule
 & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion}\\
\midrule
$\textit{Full dataset}$ &  & \\
Control & 25.10 (11.74) & 24.17 (7.02)\\
No-Practice & 37.94 (16.26) & 28.66 (13.39)\\
Unspecific-Practice & 34.46 (14.14) & 26.46 (15.02)\\
Practice & 38.74 (13.08) & 24.59 (9.34)\\
Transfer & 56.16 (18.32) & 26.51 (7.93)\\
$\textit{Nonrevealed transitions}$ &  & \\
Control & 25.10 (11.74) & 24.17 (7.02)\\
No-Practice & 29.20 (18.56) & 31.90 (14.01)\\
Unspecific-Practice & 30.38 (15.48) & 29.34 (14.06)\\
Practice & 29.63 (14.62) & 26.81 (11.35)\\
Transfer & 45.68 (24.66) & 43.95 (17.03)\\
$\textit{Revealed, but nonpracticed transitions}$ &  & \\
No-Practice & 47.64 (39.71) & 24.65 (31.82)\\
Unspecific-Practice & 33.91 (32.58) & 20.07 (26.96)\\
Transfer & 59.65 (33.59) & 16.72 (22.52)\\
$\textit{Revealed-and-practiced transitions}$ &  & \\
Practice & 75.65 (24.96) & 15.63 (29.87)\\
Transfer & 79.51 (21.81) & 7.50 (7.13)\\
\bottomrule
\end{tabular}
\end{threeparttable}
\end{center}
\end{table}

\begin{table}
\begin{center}
\begin{threeparttable}
\caption{\label{tab:appendix-pdl7-generation}Mean percentage of regular transitions generated in Experiment 2, excluding repetions. Standard deviations are given in parentheses.}
\begin{tabular}{lllll}
\toprule
 & \multicolumn{2}{c}{Random} & \multicolumn{2}{c}{Probabilistic} \\
\cmidrule(r){2-3} \cmidrule(r){4-5}
Condition & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion} & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion}\\
\midrule
$\textit{Full dataset}$ &  &  &  & \\
No transition revealed & 17.06 (8.64) & 18.94 (10.99) & 25.80 (19.20) & 23.37 (10.16)\\
One transition revealed & 30.00 (14.91) & 15.26 (10.44) & 41.56 (15.60) & 22.38 (11.58)\\
$\textit{Nonrevealed transitions}$ &  &  &  & \\
No transition revealed & 17.06 (8.64) & 18.94 (10.99) & 25.80 (19.20) & 23.37 (10.16)\\
One transition revealed & 18.46 (17.67) & 16.80 (11.47) & 31.29 (17.49) & 25.82 (14.26)\\
$\textit{Revealed transitions}$ &  &  &  & \\
One transition revealed & 79.37 (24.65) & 8.74 (11.51) & 86.75 (20.28) & 6.77 (12.20)\\
\bottomrule
\end{tabular}
\end{threeparttable}
\end{center}
\end{table}

\begin{table}
\begin{center}
\begin{threeparttable}
\caption{\label{tab:appendix-pdl10-generation}Mean percentage of regular transitions generated in Experiment 3, excluding repetions and reversals. Standard deviations are given in parentheses.}
\begin{tabular}{lllllll}
\toprule
 & \multicolumn{2}{c}{Random} & \multicolumn{2}{c}{Mixed SOC} & \multicolumn{2}{c}{Pure SOC} \\
\cmidrule(r){2-3} \cmidrule(r){4-5} \cmidrule(r){6-7}
Condition & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion} & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion} & \multicolumn{1}{c}{Inclusion} & \multicolumn{1}{c}{Exclusion}\\
\midrule
$\textit{Full dataset}$ &  &  &  &  &  & \\
No transition revealed & 26.57 (9.25) & 23.16 (9.58) & 28.43 (11.07) & 25.11 (9.51) & 28.85 (13.03) & 25.98 (9.13)\\
Two transitions revealed & 34.27 (8.75) & 25.82 (6.00) & 38.87 (10.47) & 27.02 (10.85) & 34.26 (8.86) & 29.54 (8.93)\\
$\textit{Nonrevealed transitions}$ &  &  &  &  &  & \\
No transition revealed & 26.57 (9.25) & 23.16 (9.58) & 28.43 (11.07) & 25.11 (9.51) & 28.85 (13.03) & 25.98 (9.13)\\
Two transitions revealed & 19.54 (8.86) & 24.46 (7.59) & 27.05 (11.64) & 27.19 (8.94) & 22.01 (9.61) & 27.93 (7.63)\\
$\textit{Revealed transitions}$ &  &  &  &  &  & \\
Two transitions revealed & 78.73 (28.18) & 28.90 (31.97) & 80.02 (21.62) & 24.59 (27.24) & 78.64 (26.53) & 29.92 (31.57)\\
\bottomrule
\end{tabular}
\end{threeparttable}
\end{center}
\end{table}

\section{Additional model analyses}\label{additional-model-analyses}

\setlength{\parindent}{0.5in} \setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}

This appendix provides results of additional model analyses not included
in the main text.

\subsection{\texorpdfstring{Experiment 1, model
\(\mathcal{M}_1\)}{Experiment 1, model \textbackslash{}mathcal\{M\}\_1}}\label{experiment-1-model-mathcalm_1}

In Experiment 1, we fitted model \(\mathcal{M}_1\) and used posterior
analyses to evaluate the invariance assumption. We adapted the equations
from Experiment 2 to the design of Experiment 1 (which did not contain
experimental groups with random material). In order to accommodate for
the more complex design, we used a model specification that allowed for
participant and item (i.e., transition) effects and their interactions
by estimating fixed effects for each transition type plus individual
participants' deviations from these effects. The model equations of
model \(\mathcal{M}_1\) are given by:

\[
  C_{ijm} = \begin{cases}
    \Phi(\mu_{jlm}^{(C)} + \delta_{ijm}^{(C)}) & \text{if } j \epsilon 1, 2 \text{ (item has been revealed \& practiced, revealed \& non-practiced)}\\
                                              0 & \text{if }j=3 \text{ (item has not been revealed)}\\
    \end{cases}
\] and \[
  A_{imt} = \Phi(\mu_{mt}^{(A)} + \delta_{imt}^{(A)})
\] where \(\mu_{jlm}^{(C)}\) is the fixed effect of transition type
\(j\) (non-revealed, revealed \& practiced, revealed \& non-practiced)
in condition \(l\) and \emph{PD instruction} condition \(m\) on
controlled processes, and \(\delta_{ijm}^{(C)}\) is the \(i\)th
participant's deviation from the corresponding mean. Accordingly,
\(\mu_{mt}^{(A)}\) is the fixed effect of \emph{PD instruction}
condition \(m\) and transition \(t\) on automatic processes, and
\(\delta_{imt}^{(A)}\) is the \(i\)th participant's deviation from the
corresponding mean.

Model \(\mathcal{M}_1\) imposes two auxiliary assumptions: First, it
assumed that no explicit knowledge has been acquired during the SRT
phase (i.e., \(C=0\) for non-revealed transitions). Second, it assumed
that revealing sequence knowledge did not affect automatic processes
(i.e., \(A\) does not vary as a function of the between-subjects
manipulation of explicit knowledge, index \(l\)). Both auxiliary
assumptions were tested by posterior predictive checks. In addition to
reporting \(T_{A1}\) and \(T_{B1}\) as in Experiments 2 and 3, we
calculated additional model check statistic \(T_{A2}\), which summarizes
how well the model describes the item-wise category counts (aggregated
over participants), and \(T_{A3}\), which summarizes how well the model
describes the category counts per participant-item combination; finally,
the additional statistic \(T_{B2}\) summarizes how well the model
describes the variances and covariances introduced by items. We also
calculated the posterior differences \(C_I - C_E\) and \(A_I - A_E\) to
more directly test the invariance assumption.

\subsubsection{Results}\label{results}

We analyzed generation performance by fitting \(\mathcal{M}_1\) and
computed model fit statistics to assess whether each model can account
for the data. Parameter estimates from model \(\mathcal{M}_1\) were used
to address the invariance assumptions, directly. The first trial of a
block as well as any response repetitions were excluded from all
generation task analyses.

The model checks for model \(\mathcal{M}_1\) were satisfactory,
\[T_{A1}^{observed} = 35.97, T_{A1}^{expected} = 33.96, p = .322,\]~
\[T_{A2}^{observed} = 0.05, T_{A2}^{expected} = 0.05, p = .480,\]~
\[T_{A3}^{observed} = 1,763.79, T_{A3}^{expected} = 1,720.63, p = .372,\]~
\[T_{B1}^{observed} = 5.31, T_{B1}^{expected} = 4.62, p = .457,\]~
\[T_{B2}^{observed} = 3,852.65, T_{B2}^{expected} = 3,393.90, p = .464.\]

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl9-parameter-estimates-1.pdf}
\caption{(\#fig:pdl9-parameter-estimates)Parameter estimates from
Experiment 1, model \(\mathcal{M}_1\). Error bars represent 95\%
confidence intervals.}
\end{figure}

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl9-posterior-differences-1.pdf}
\caption{(\#fig:pdl9-posterior-differences)Posterior differences between
\(A_I - A_E\) and \(C_I - C_E\) in Experiment 1, plotted for each
participant (gray dots) with 95\% credible intervals. Dashed lines
represent the posterior means of the differences between mean parameter
estimates. Dotted lines represent 95\% credible intervals.}
\end{figure}

Figure @ref(fig:pdl9-parameter-estimates) shows the parameter estimates
obtained from model \(\mathcal{M}_1\); while estimates of the automatic
process were only slightly above chance in both \emph{PD instruction}
conditions, estimates of the controlled process differ strongly between
\emph{PD instruction} conditions.

Figure @ref(fig:pdl9-posterior-differences) shows that the invariance
assumption for automatic processes was violated with \(A_I > A_E\), 95\%
CI {[}.00, .03{]}, and Bayesian \(p = .008\). For revealed and practiced
transitions, the invariance assumption was violated with \(C_I > C_E\),
95\% CI {[}.19, .63{]} and a Bayesian \(p = .001\). For revealed but
non-practiced transitions, the invariance assumption was violated with
\(C_I > C_E\), 95\% CI {[}.03, .31{]} and a Bayesian \(p = .005\).

\subsection{\texorpdfstring{Experiment 2, model
\(\mathcal{M}_{1R}\)}{Experiment 2, model \textbackslash{}mathcal\{M\}\_\{1R\}}}\label{experiment-2-model-mathcalm_1r}

To test whether our results are robust against changes in auxiliary
assumptions, we fitted another model \(\mathcal{M}_{1R}\) with different
auxiliary assumptions. Specifically, we dropped the assumption that
\(C=0\) for nonrevealed transitions and instead estimated
explicit-knowledge parameters for all transitions. Instead, we imposed
ordinal restrictions (Knapp \& Batchelder, 2004) as follows: In model
\(\mathcal{M}_{1R}\), it is assumed that \(C\) parameters are greater
under inclusion than exclusion. We also fitted a parallel model with the
reversed assumption, but estimation of this model failed to converge.

The second-level equations of model \(\mathcal{M}_{1R}\) are given by:

\[
  \begin{aligned}
  C_{ij1} &= C_{ij, Inclusion} &= \Phi(\mu_{jk,Inclusion}^{(C)} + \delta_{ij, Inclusion}^{(C)})& \\
  C_{ij2} &= C_{ij, Exclusion} &= \Phi(\mu_{jk,Exclusion}^{(C)} + \delta_{ij, Exclusion}^{(C)})& * C_{ij, Inclusion}
  \end{aligned}
\] and

\[
  A_{ijm} = \Phi(\mu_{jkm}^{(A)} + \delta_{ijm}^{(A)})
\] \(\mu_{jkm}^{(C)}\) is the fixed effect of material \(k\) (that
participant \(i\) worked on during the SRTT), \emph{transition type}
\(j\) (\(j = 1\) if a transition has actually been revealed, \(j=2\) if
not), and \emph{PD instruction} condition \(m\) on controlled processes.
\(\delta_{ijm}^{(C)}\) is the \(i\)th participant's deviation from the
respective group mean. For participants who did not receive explicit
knowledge about a single transition, we assumed that all
\(\mu_{jk, Inclusion}^{(C)} = \mu_{k, Inclusion}^{(C)}\) and
\(\mu_{jk, Exclusion}^{(C)} = \mu_{k, Exclusion}^{(C)}\), i.e.~we
assumed that the grand mean of explicit knowledge did not vary as a
function of the transition that \emph{would} have been revealed if
participants \emph{were} in another condition. Accordingly,
\(\mu_{jkm}^{(A)}\) is the fixed effect of transition type \(j\)
(\(j = 1\) for the transition that was or \emph{would} have been
revealed, i.e.~transition \(2{-}6\), \(j=2\) for all other transitions),
material \(k\), and \emph{PD instruction} condition \(m\) on automatic
processes, and \(\delta_{ijm}^{(A)}\) is the \(i\)th participant's
deviation from the corresponding mean.

Note that this specification imposes two auxiliary assumptions to the
model: First, it is assumed that
\[\forall{ij}(C_{ij, \textit{Inclusion}} \geq C_{ij, \textit{Exclusion}})\]
Second, it is assumed that automatic processes \(A\) do not vary as a
function of the between-subjects manipulation of explicit knowledge
\(l\) (both assumptions were necessary so that the model was identified;
an alternative model imposing an order constraint \(C_I < C_E\) was also
not identified).

\subsubsection{Results}\label{results-1}

The model checks for model \(\mathcal{M}_{1R}\) were satisfactory,
\[T_{A1}^{observed} = 484.60, T_{A1}^{expected} = 470.11, p = .409,\]~
\[T_{B1}^{observed} = 9.13, T_{B1}^{expected} = 6.88, p = .358.\] and
attained a DIC value of \(25{,}294.53\), a value comparable to our
extended model \(\mathcal{M}_{1}\) presented in the main text and
clearly outperforming \(\mathcal{M}_2\). This again implies that our
auxiliary assumptions introduced to \(\mathcal{M}_{1R}\) were much less
problematic than the invariance assumption.

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl7-m1r-parameter-estimates-1.pdf}
\caption{(\#fig:pdl7-m1r-parameter-estimates)Parameter estimates from
Experiment 2, model \(\mathcal{M}_{1R}\). Error bars represent 95\%
confidence intervals.}
\end{figure}

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl7-m1r-posterior-differences-1.pdf}
\caption{(\#fig:pdl7-m1r-posterior-differences)Posterior differences
between \(A_I - A_E\) and \(C_I - C_E\) in Experiment 2, model
\(\mathcal{M}_{1R}\), plotted for each participant (gray dots) with 95\%
credible intervals. Dashed lines represent the posterior means of the
differences between mean parameter estimates. Dotted lines represent
95\% credible intervals.}
\end{figure}

Figure @ref(fig:pdl7-m1r-parameter-estimates) shows the parameter
estimates obtained from model \(\mathcal{M}_{1R}\). The pattern of
results mostly replicates the estimates from model \(\mathcal{M}_1\).
The main difference was that \(C\) parameters were slightly greater than
zero for nonrevealed transitions (these were set to zero for model
\(\mathcal{M}_1\)). This may suggest that some explicit knowledge may
have been acquired during the learning phase. Alternatively, it may also
reflect a technical issue with the present family of models that biases
estimates away from zero: Specifically, for nonrevealed transitions, the
inclusion-exclusion difference in \(C\) estimates should vary around
zero, with half below zero and half above zero; the auxiliary assumption
however forces all of them to be positive, which biases the
corresponding \(C\) parameters. Either way, the effect is not
substantial, as suggested by the finding that model \(\mathcal{M}_1\),
which assumes \(C=0\), achieved an equally good fit. The \(C>0\)
estimates also have a tradeoff effect on \(A\) parameters, with lower
estimates under inclusion and slightly higher estimates under exclusion.
This biasing effect eliminated (for revealed transitions) or even
inverted (for nonrevealed transitions) the invariance-violation effect
found in \(\mathcal{M}_1\).

Figure @ref(fig:pdl7-m1r-posterior-differences) shows the posterior
differences obtained from model \(\mathcal{M}_{1R}\). Most importantly,
the pattern of results shows that the invariance violation for
controlled processes \(C\) for revealed transitions (i.e., whenever
substantial explicit knowledge is present) is robust to the change in
auxiliary assumptions.

\subsection{\texorpdfstring{Experiment 3, model
\(\mathcal{M}_{1R}\)}{Experiment 3, model \textbackslash{}mathcal\{M\}\_\{1R\}}}\label{experiment-3-model-mathcalm_1r}

For the data of Experiment 3, we additionally fitted model
\(\mathcal{M}_{1R}\) analogous to \(\mathcal{M}_{1R}\) of Experiment 2.

\subsubsection{Results}\label{results-2}

The model checks for model \(\mathcal{M}_{1R}\) were satisfactory,
\[T_{A1}^{observed} = 689.87, T_{A1}^{expected} = 657.24, p = .314,\]~
\[T_{B1}^{observed} = 8.94, T_{B1}^{expected} = 6.02, p = .263.\] and
attained a DIC value of \(38{,}881.68\), a value somewhat smaller than
the DIC of our extended model \(\mathcal{M}_{1}\) presented in the main
text and clearly outperforming \(\mathcal{M}_2\). This again implies
that our auxiliary assumptions introduced to \(\mathcal{M}_{1R}\) were
much less problematic than the invariance assumption.

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl10-m1r-parameter-estimates-1.pdf}
\caption{(\#fig:pdl10-m1r-parameter-estimates)Parameter estimates from
Experiment 3, model \(\mathcal{M}_{1R}\). Error bars represent 95\%
confidence intervals.}
\end{figure}

\begin{figure}
\centering
\includegraphics{main_files/figure-latex/pdl10-m1r-posterior-differences-1.pdf}
\caption{(\#fig:pdl10-m1r-posterior-differences)Posterior differences
between \(A_I - A_E\) and \(C_I - C_E\) in Experiment 3, model
\(\mathcal{M}_{1R}\), plotted for each participant (gray dots) with 95\%
credible intervals. Dashed lines represent the posterior means of the
differences between mean parameter estimates. Dotted lines represent
95\% credible intervals.}
\end{figure}

Figure @ref(fig:pdl10-m1r-parameter-estimates) shows the parameter
estimates obtained from model \(\mathcal{M}_{1R}\). The pattern of
results mostly replicates the estimates from model \(\mathcal{M}_1\);
with parameters for controlled processes \(C\) being estimated close to
zero for nonrevealed transitions.

Figure @ref(fig:pdl10-m1r-posterior-differences) shows the posterior
differences obtained from model \(\mathcal{M}_{1R}\). The pattern of
results again demonstrates robustness of the invariance violation for
controlled processes \(C\) for revealed transitions (i.e., whenever
substantial explicit knowledge was present). There was again some
indication of an invariance violation for automatic processes \(A\);
however, the effect was very small and depended on the specific modeling
assumptions.

\section{Specification of priors}\label{specification-of-priors}

This section provides a complete specification of the models and priors
used. Code (\textbf{\textsf{R}}/\textbf{\textit{Stan}}) is available at
\url{https://github.com/methexp/pdl2}.

\subsection{\texorpdfstring{Experiment 1, model
\(\mathcal{M}_1\)}{Experiment 1, model \textbackslash{}mathcal\{M\}\_1}}\label{experiment-1-model-mathcalm_1-1}

Priors on fixed effects were

\[
\begin{aligned}
\mu_{jlm}^{(C)} & \sim N(0, 1), j = \lbrace 1, 2 \rbrace; l = \lbrace 1, 2 \rbrace; m = \lbrace 1, 2 \rbrace\\
\mu_{mt}^{(A)} & \sim N(0, 1), t = \lbrace 1, ..., 6 \rbrace ; m = \lbrace 1, 2 \rbrace\\
\end{aligned}
\]

where \(j\) indexes \emph{transition type} (revealed \& practiced
vs.~revealed \& non-practiced), \(l\) indexes practice condition
(Control, No-practice, Unspecific-practice, Practice, Transfer), \(t\)
indexes specific items (i.e., transitions), and \(m\) indexes \emph{PD
instruction} (inclusion vs.~exclusion). Participant effects
\(\delta_{imt}^{(A)}\) and \(\delta_{ijm}^{(C)}\) can be written as
vectors \(\boldsymbol{\delta}_i\). For participants in the
\emph{Control} group, these were modeled by \[
\boldsymbol{\delta}_i \sim N_{12} (0, \Sigma_l), i = 1, ..., I
\] For participants in the \emph{No-Practice},
\emph{Unspecific-Practice}, and \emph{Practice} groups, \[
\boldsymbol{\delta}_i \sim N_{14} (0, \Sigma_l), i = 1, ..., I
\] For participants in the \emph{Transfer} group \[
\boldsymbol{\delta}_i \sim N_{16} (0, \Sigma_l), i = 1, ..., I
\] The covariance matrices \(\Sigma_l\) were modeled separately and
independently for each between-subjects condition. Priors on these
matrices were as described below for Experiment 2.

\subsection{\texorpdfstring{Experiment 2, model
\(\mathcal{M}_1\)}{Experiment 2, model \textbackslash{}mathcal\{M\}\_1}}\label{experiment-2-model-mathcalm_1}

Priors on fixed effects were

\[
\begin{aligned}
\mu_{km}^{(C)} \sim & N(0, 1), k = \lbrace 1, 2 \rbrace; m = \lbrace 1, 2 \rbrace\\
\mu_{jkm}^{(A)} \sim & N(0, 1), j = \lbrace 1, 2 \rbrace; k = \lbrace 1, 2 \rbrace; m = \lbrace 1, 2 \rbrace
\end{aligned}
\] where \(j\) indexes transition type (revealed vs.~non-revealed),
\(k\) indexes learning material presented during the SRTT (random
vs.~probabilistic), and \(m\) indexes \emph{PD instruction} condition
(inclusion vs.~exclusion). For participants who did not receive explicit
knowledge about a single transition, we assumed that all
\(C_{ijkm} = 0\). Therefore, participant effects are only required for
automatic processes (\(\delta_{ijkm}^{(A)}\)). In participants who
received explicit knowledge about one transition, two additional
participant effects were needed to model controlled processes for
revealed transitions (\(\delta_{ikm}^{(C)}\)). We thus provide the
specification of participant effects for these two groups of
participants separately.

\paragraph{Participants who did not receive explicit knowledge about one
transition}\label{participants-who-did-not-receive-explicit-knowledge-about-one-transition}

For participants who did not receive explicit knowledge about one
transition, participant effects \(\delta_{ijm}^{(A)}\) can be written as
vectors \(\boldsymbol{\delta}_i\) that were modeled as draws from a
multivariate normal

\[
\boldsymbol{\delta}_i \sim N_4 (0, \Sigma_{kl}), i = 1, ..., I
\] where \(k\) indexes the learning material that was presented to
participant \(i\) and \(l\) indexes his or her level of the
explicit-knowledge factor. The covariance matrices \(\Sigma_{kl}\) were
obtained from the standard deviations of participant effects
\(\boldsymbol{\sigma}_{kl}\) and correlation matrices \(\Omega_{kl}\)

\[
\Sigma_{kl} = Diag(\boldsymbol{\sigma}_{kl})~\Omega_{kl}~Diag(\boldsymbol{\sigma}_{kl}), k = \lbrace 1, 2 \rbrace, l = \lbrace 1, 2 \rbrace
\] Each element \(\sigma_{klp}\) of the vectors of standard deviations
\(\boldsymbol{\sigma}_{kl}\) was drawn from independent half-normal
prior distributions.

\[
\sigma_{klp} \sim N (0, 1)_{\mathcal{I}(0, \infty)}, k = \lbrace 1, 2 \rbrace, l = \lbrace 1, 2 \rbrace
\] For the correlation matrices \(\Omega_{k}\), we used LKJ priors with
a scaling factor of 1 (Lewandowski, Kurowicka, \& Joe, 2009):

\[
\Omega_{kl} \sim \textit{LKJcorr}(\nu = 1), k = \lbrace 1, 2 \rbrace, l = \lbrace 1, 2 \rbrace
\]

\paragraph{Participants who received explicit knowledge about one
transition}\label{participants-who-received-explicit-knowledge-about-one-transition}

For participants who received explicit knowledge about one transition,
participant effects \(\delta_{ijm}^{(A)}\) and \(\delta_{im}^{(C)}\) can
be written as vectors \(\boldsymbol{\delta}_i\) that were modeled as
draws from a multivariate normal

\[
\boldsymbol{\delta}_i \sim N_6 (0, \Sigma_{kl}), i = 1, ..., I
\] where \(k\) indexes the learning material that was presented to
participant \(i\) and \(l\) indexes his or her level of the
explicit-knowledge factor. The covariance matrices \(\Sigma_kl\) were
specified as above, with the only exception that six instead of four
parameters were required.

\subsection{\texorpdfstring{Experiment 2, model
\(\mathcal{M}_2\)}{Experiment 2, model \textbackslash{}mathcal\{M\}\_2}}\label{experiment-2-model-mathcalm_2}

Priors on fixed effects were

\[
\begin{aligned}
\mu_{jkl}^{(C)} \sim & N(0, 1), j = \lbrace 1, 2 \rbrace; k = \lbrace 1, 2 \rbrace; l = \lbrace 1, 2 \rbrace\\
\mu_{jkl}^{(A)} \sim & N(0, 1), j = \lbrace 1, 2 \rbrace; k = \lbrace 1, 2 \rbrace; l = \lbrace 1, 2 \rbrace\\
\end{aligned}
\] Participant effects \(\delta_{ij}^{(A)}\) and \(\delta_{ij}^{(C)}\)
can be written as vectors \(\boldsymbol{\delta}_i\) that were modeled by
\[
\boldsymbol{\delta}_i \sim N_4 (0, \Sigma_{kl}), i = 1, ..., I
\] Priors for the covariance matrix \(\Sigma_{kl}\) were specified as
above.

\subsection{\texorpdfstring{Experiment 2, model
\(\mathcal{M}_{1R}\)}{Experiment 2, model \textbackslash{}mathcal\{M\}\_\{1R\}}}\label{experiment-2-model-mathcalm_1r-1}

Priors on fixed effects were

\[
\begin{aligned}
\mu_{jkm}^{(C)} \sim & N(0, 1), j = \lbrace 1, 2 \rbrace; k = \lbrace 1, 2 \rbrace; m = \lbrace 1, 2 \rbrace\\
\mu_{jkm}^{(A)} \sim & N(0, 1), j = \lbrace 1, 2 \rbrace; k = \lbrace 1, 2 \rbrace; m = \lbrace 1, 2 \rbrace
\end{aligned}
\] where \(j\) indexes transition type (revealed vs.~non-revealed),
\(k\) indexes learning material presented during the SRTT (random
vs.~probabilistic), and \(m\) indexes \emph{PD instruction} condition
(inclusion vs.~exclusion). Participant effects \(\delta_{ijm}^{(A)}\)
and \(\delta_{ijm}^{(C)}\) can be written as vectors
\(\boldsymbol{\delta}_i\) that were modeled as draws from a multivariate
normal

\[
\boldsymbol{\delta}_i \sim N_8 (0, \Sigma_{kl}), i = 1, ..., I
\] where \(k\) indexes the learning material that was presented to
participant \(i\) and \(l\) indexes his or her level of the
explicit-knowledge factor. Priors for the covariance matrix
\(\Sigma_{kl}\) were specified as above.

\subsection{\texorpdfstring{Experiment 3, models \(\mathcal{M}_1\),
\(\mathcal{M}_2\), and
\(\mathcal{M}_{1R}\)}{Experiment 3, models \textbackslash{}mathcal\{M\}\_1, \textbackslash{}mathcal\{M\}\_2, and \textbackslash{}mathcal\{M\}\_\{1R\}}}\label{experiment-3-models-mathcalm_1-mathcalm_2-and-mathcalm_1r}

For the model-based analyses, we used models \(\mathcal{M}_1\),
\(\mathcal{M}_2\), and \(\mathcal{M}_{1R}\) analogous to those used in
Experiment 2.
\end{appendix}
