---
title: "Assumptions of the process-dissociation procedure are violated in implicit sequence learning"
shorttitle: "Process-dissociation assumptions in sequence learning"
author: 
  - name: Marius Barth
    affiliation: ""
    corresponding: yes    # Define only one corresponding author
    address: Herbert-Lewin-Str. 2, D-50931 Köln, Germany
    email: marius.barth@uni-koeln.de
  - name: Christoph Stahl
    affiliation: ""
  - name: Hilde Haider
    affiliation: ""
affiliation:
  - id: ""
    institution: University of Cologne

abstract: |
  In implicit sequence learning, a process-dissociation (PD) approach has been proposed to dissociate implicit and explicit learning processes. Applied to the popular generation task, participants perform two different task versions: *inclusion* instructions require generating the transitions that form the learned sequence; *exclusion* instructions require generating transitions other than those of the learned sequence. Whereas accurate performance under inclusion may be based on either implicit or explicit knowledge, avoiding to generate learned transitions requires controllable explicit sequence knowledge. The PD approach yields separate estimates of explicit and implicit knowledge that are derived from the same task; it therefore avoids many problems of previous measurement approaches. However, the PD approach rests on the critical assumption that the implicit and explicit processes are invariant across inclusion and exclusion conditions. We tested whether the invariance assumption holds for the PD generation task. Across three studies using first-order as well as second-order regularities, invariance of the controlled process was found to be violated. In particular, despite extensive amounts of practice, explicit knowledge was not exhaustively expressed in the exclusion condition. We discuss the implications of these findings for the use of process-dissociation in assessing implicit knowledge.

note: |
  *(Unpublished manuscript, 2017-08-24)*.

author_note: |  
  Marius Barth, Christoph Stahl, Hilde Haider, Department of Psychology, University of Cologne. 
  
  CS and HH designed the research; MB, CS, and HH planned the studies; MB conducted the studies; MB and CS analyzed the data; MB, CS, and HH wrote the paper. We thank Jan Czarnomski, Conni Lebbing, Friederike Neugebauer, and Imge Ürer for help with data collection.

  This work was funded by Deutsche Forschungsgemeinschaft grant STA-1269/1-1 to CS and grant HA-5447/8-1 to HH. 
  
  Data, code, and materials necessary to reproduce the analyses reported in this article are available at https://github.com/methexp/pdl2.
  
keywords: "sequence learning, process-dissociation procedure, invariance assumption"

wordcount: "15,777"

class: man
figsintext: no
lineno: no
keep_tex: yes
bibliography:
  - additional_references.bib
  - zotero_references.bib
  - r-references.bib
nocite: |
  - @lewandowski_generating_2009
  - @knapp_representing_2004

output:
  papaja::apa6_pdf:
    includes:
      after_body: appendix.tex

---


```{r 'init', message = FALSE, warning = FALSE}
rm(list=ls())

# Load libraries
library("papaja")
library("afex")
library("rstan")

# Set chunk defaults
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 8.8, fig.height = 5, dev = "pdf", cache = FALSE, par = TRUE)

# Set global defaults for plotting
knitr::knit_hooks$set(par = function(before, options, envir){
if (before && options$fig.show!='none') par(mar = c(5.4, 4, 2, 0)+.1, las = 1, font.main = 1, cex.main = 1.05)
})


# Set default contrasts to contr.sum
set_sum_contrasts()

source("R/aggregate.R")
source("R/anova.R")
source("R/barplot.R")
source("R/t.test.R")
source("R/PudelHelper.R")
source("R/PDhelper.R")
```


```{r child="introduction.rmd"}
```


# Experiment 1

```{r child="pdl9.rmd"}
```


# Experiment 2

```{r child="pdl7.rmd"}
```


# Experiment 3

```{r child="pdl10.rmd"}
```


# General Discussion

```{r child = "discussion.rmd"}
```


\clearpage

# References
```{r 'references', warning=FALSE, cache=FALSE}
r_refs(file = "r-references.bib")
render_appendix("appendix.rmd")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
